### PR TITLE
Supports displaying short links

### PR DESCRIPTION
**Pull request by AKEB**
Supports displaying short links for easy downloading on TVs and Android TVs

## Description

This setting shows a short link on the page to download the config file

## Motivation and Context

This is to make it convenient for Android TVs to type in a short address and download the config file

## How has this been tested?

I tested this on my server, and on my laptop. By adding the UI_SHOW_LINKS parameter to the docker-compose.dev.yml file with different values I looked at the result of the page after restarting the container

## Screenshots (if appropriate):

Screenshot at Aug 16 18-42-33

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pheiduck** [comment]
I don't know what this will add for the users, due a config download button already exists.

**Comment by pheiduck** [comment]
@AKEB please fix lint errors

**Comment by AKEB** [comment]
Done

**Comment by pheiduck** [comment]
For the next time use a sperate branch thanks!

**Review by pheiduck — APPROVED** [review]

**Comment by AKEB** [comment]
> @pheiduck this has to be fixed (security issue) the route is not checked using the middleware therefore anyone could bruteforce a 8 character hex string and download the config. also maybe something like `/cnf/:clientHash` should be used to avoid name clash when multiple pages are introduced or the router gets confused

Thank you for the comment. To be fixed here https://github.com/wg-easy/wg-easy/pull/1301

**Pull request merged**
