### PR TITLE
 Version 14: Home Assistent support, PASSWORD_HASH (inc. Helper), translation updates, bugfixes and more

### PR DESCRIPTION
**Pull request by pheiduck**
### Stable Release: 2024-08-09

**Attention before you update to the new version you should disconnect your instance from the internet because PASSWORD has been replaced by PASSWORD_HASH. You can find more information here: [How to generate an bcrypt hash](https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md)**

- https://github.com/wg-easy/wg-easy/pull/1080
- https://github.com/wg-easy/wg-easy/pull/1116
- https://github.com/wg-easy/wg-easy/pull/1180
- https://github.com/wg-easy/wg-easy/pull/1145

Full list: https://github.com/wg-easy/wg-easy/milestone/3?closed=1

Thanks to all contributors to get us able to release v14!
v14 Feature Window is closed now, focus on testing and bug fixes if needed.
Feedback of our nightly users are welcome!

### CODE REVIEW

**Comment by pheiduck** [comment]
> many new features are expected for 15. so 14 should be released.
> 
> what is blocking this (other than release date (maybe release it earlier?))

Release is rescheduled for friday next week.

**Comment by somejavadev** [comment]
I see the release mentions `Home Assistent support` is there perhaps any documentation on this?

**Comment by somejavadev** [comment]
Thanks @pheiduck, @adriy-be is the home assistant integration documented anywhere? I see it's the first thing mentioned in the release but I don't see any code in the 14th release specific to it or any documentation referencing it.

**Comment by adriy-be** [comment]
@somejavadev you can follow : https://github.com/jdeath/homeassistant-addons/tree/main/wgeasy

**Pull request merged**
