### PR TITLE
[Feature] Add dark mode

### PR DESCRIPTION
**Pull request by goodbyepavlyi**
Based on: https://github.com/WeeJeWel/wg-easy/pull/178

This PR contains the following changes:

- Add dark mode using the new `dark:` class in Tailwind 3.
- Add theme switch button.
- Fix static HTML elements flashing when reloading page.
- Fix mobile layout and overflowing elements.

This PR also changes a few things in light mode:

- Removed the double border from the `Clients` header.
- Removed the bottom border/divider from the last table child.

### Screenshots:
image
image
image

### CODE REVIEW

**Comment by megoRU** [comment]
The color scheme and the color of the buttons are better here: https://github.com/WeeJeWel/wg-easy/pull/178

**Comment by goodbyepavlyi** [comment]
I agree, but since the author said they don't like it or something like that I thought to recreate it in different color scheme.

**Comment by WeeJeWel** [comment]
This looks really good! I’ll take a closer look and try to merge it when I have some free time.

**Comment by DJBenson** [comment]
Cheers for this - in the absence of official support, I've built this locally and am using it in my environment.

**Comment by unclamped** [comment]
Oh my god WHAT, I did not know that there was a sign-in button and text below it on the login page, or that it was inside a box at all! It's completely invisible from where I'm looking.
This PR is a must, not only for the sake of some's eyes but also for something like this. The light version colors are almost identical to each other and some elements can't even be seen.

**Comment by Bark33p3r** [comment]
Any news on this topic? @WeeJeWel

**Comment by WeeJeWel** [comment]
Not really, sorry. I think this project is useful enough for most people, and I have other more impactful things to work on right now than a color scheme for an admin tool you visit sporadically.

If you like this PR, you can build the fork and use it already! :)

**Comment by bigahuna** [comment]
> Not really, sorry. I think this project is useful enough for most people, and I have other more impactful things to work on right now than a color scheme for an admin tool you visit sporadically.

There are nice browserplugins that provide dark mode for all websites. I.e. https://github.com/darkreader/darkreader for firefox and chrome. I'm also happy if this project keeps focus on the important stuff and does not get sidetracked on design issues...

**Comment by peterlewis** [comment]
Thanks for this work @goodbyepavlyi! Spoke with @WeeJeWel and @pheiduck earlier about this. I gather that @pheiduck merged-in this PR downstream and it has been proposed to be a veritable salmon of the code snipped world, and make it back upstream! :)

So as to keep buttons to a minimum, prior to merge we're keen to move from a `class`-based approach to using `media`, so as to align to whatever the user has set in their desktop environment.

Will get cracking on that ASAP!

**Comment by peterlewis** [comment]
Thank you so much for your contribution @goodbyepavlyi. This feature is to be added in version 9 (which is currently in `nightly`).

**Pull request closed without merging**
