### PR TITLE
Feat: UI, General Improvements

### PR DESCRIPTION
**Pull request by kaaax0815**
## Description

TODO

## Motivation and Context

TODO

## How has this been tested?

TODO

## Screenshots (if appropriate):
TODO

## Tracker
- [x] Features (toggle features)
- [x] Account (change email, username, password, etc)
- [ ] WireGuard (cidr, port, iptables, etc)
- [ ] Settings (language, session timeout, etc)
- [ ] Metrics (Prometheus, own category for future use)
- [ ] Setup Migration
- [ ] Client Create/Edit UI
- [ ] Replace Alerts with Form Errors or Toast

### CODE REVIEW

**Comment by kaaax0815** [comment]
@tetuaoro This still needs a lot of work

**Comment by aalvarado** [comment]
This is looking great, thank you!

**Comment by kaaax0815** [comment]
Bildschirmfoto 2024-09-20 um 14 45 29

@tetuaoro @pheiduck what do you think. a little inspiration from v0

**Comment by tetuaoro** [comment]
> @tetuaoro @pheiduck what do you think. a little inspiration from v0

I like the new ui. So, rework like that ?

**Comment by kaaax0815** [comment]
> > @tetuaoro @pheiduck what do you think. a little inspiration from v0
> 
> I like the new ui. So, rework like that ?

First imo is https://github.com/kaaax0815/wg-easy/pull/4. Then UI for WireGuard Settings or UI for Client Edit

**Comment by aloks98** [comment]
This seems interesting, I would love to help on this. Please let me know!

**Comment by kaaax0815** [comment]
@aloks98 Would gladly accept your help. You can look at https://github.com/kaaax0815/wg-easy/pull/4 or do something different thats listed in the Tracker

**Comment by kaaax0815** [comment]
@tetuaoro Switching between Traffic Stats seems unnecessary since it only displays total bandwidth usage. Keeping it enabled all the time shouldn’t cause any issues. Additionally, the chart type should be customizable by each user rather than being set server-wide.

What do you think?

**Comment by kaaax0815** [comment]
Did some heavy refactors. I think we should move to a more acid compliant database like sqlite. If we start tracking bandwidth usage we should do that in a separate thread (query WireGuard e.g. very 10 seconds) and this would not work with lowdb.
Also with that we could support multiple interfaces sometime in the future. But not important rn

**Comment by kaaax0815** [comment]
Merging to update base branch

**Comment by qvipin** [comment]
ooo man soo excited

**Pull request merged**
