### PR TITLE
Add custom port and interface

### PR DESCRIPTION
**Pull request by Comet1903**
When using wg-easy with the `network_mode: host` (or `--net=host`) option, you can't claim a interface name twice. Also the port can't be claimed twice. Now you can change the name of the interface and the port for the "server" within the container.

### CODE REVIEW

**Comment by peterlewis** [comment]
Hey! Thanks for raising the missing `$WG_PORT` variable. I'm hopeful this fix may resolve https://github.com/wg-easy/wg-easy/issues/692!

**Comment by peterlewis** [comment]
Please can you split this PR so that the missing `$WG_PORT` is separate to the interface variable? Thanks!

**Comment by pheiduck** [comment]
@Comet1903 Thanks for your PR!
I fixed up the lint errors which where reported by Lint CI.

**Comment by pheiduck** [comment]
@Comet1903 can you please deploy a dev build in your fork and test it?

**Comment by peterlewis** [comment]
Looks good! Still keen to split-out the fix from the enhancement, in terms of PR, if @Comet1903 is happy to oblige.

**Comment by Comet1903** [comment]
> @Comet1903 can you please deploy a dev build in your fork and test it?

@pheiduck I'm not 100% sure what you mean. I tested it on my servers and it worked for me. Is there something special I need to do that I'm not currently aware of?


> Looks good! Still keen to split-out the fix from the enhancement, in terms of PR, if @Comet1903 is happy to oblige.

@peterlewis Do I really need to split this into two pull requests, since these changes are somehow minor... If I have to, I'm happy to do that, but I don't think it's really that necessary.

**Comment by peterlewis** [comment]
@Comet1903 I completely appreciate your point. Indeed they are both minor, but as can be seen from the fact that one of the two changes in your PR corrects an omission made in a previous attempt to shift a value from constant to variable, it feels cleaner to keep the two commits separate.

I truly value your time and your generosity in using it to contribute to this project, and don't wish to waste it, so if you'd prefer, I can gladly make the changes to this PR to focus on the WG interface variable-isation (if that is, indeed, a word) but just wanted to ensure to give adequate credit wherever possible.

I hope the above helps to emphasise that the intention is purely based in/on sensibility and not pedantry! 😀 

Thanks again!

**Comment by peterlewis** [comment]
To add, I am also a big fan of democracy, so if either @WeeJeWel or @pheiduck is happy to tell me I am being overly-cautious then I am happy to "undo" what I've requested! :)

**Review by pheiduck — APPROVED** [review]

**Comment by pheiduck** [comment]
@peterlewis I agree with both changes from @Comet1903

**Comment by peterlewis** [comment]
Hey @Comet1903. Just a courtesy call to let you know that, at this time we are to revert the changes made in this PR. That isn't to say that we won't look to implement the required features, but as was pointed out by @centralhardware, without the ability to set the port within the container, this addition is somewhat moot.

We need further consideration, not on this specific element, but moreso on how we would enable the provision of port variables in the container, as to assume that internal port = `$WG_PORT` will lead to a significant breaking change for anyone who sets that variable. Hope you understand and any consideration on the issue raised at #713 would be appreciated.

**Pull request merged**
