### PR TITLE
Added simple sortation feature

### PR DESCRIPTION
**Pull request by eftas-gka**
Client list is now sorted by client name by default. I also added a control to change sortation back to address.

### CODE REVIEW

**Comment by rudasn** [comment]
Nice! Could you add a screenshot of how it looks?

Have you thought about adding more sorting options, like current status (eg. online, offline, disabled).

**Comment by WeeJeWel** [comment]
Can you share a screenshot?

**Comment by peterlewis** [comment]
Echoing @WeeJeWel's comment that a screenshot of this implemented would be greatly appreciated. Thanks!

**Comment by pheiduck** [comment]
Well we got no reply from author 🤷‍♂️

**Pull request closed without merging**
