### PR TITLE
Allow running this software as unprivilidged software

### PR DESCRIPTION
**Pull request by BrainStone**
This allows running the software as an unpriviledged user.  
All that user needs to be allowed to run these commands without password:
- `wg`
- `wg-quick`

This can be achieved by putting this in the sudoers config:

```sudo
<user>       ALL=(root)      NOPASSWD: /usr/bin/wg , /usr/bin/wg-quick
```

### CODE REVIEW

**Comment by rudasn** [comment]
Maybe this could be a simpler change, and more likely to be accepted, if instead you allowed the `wg` and `wg-quick` commands to be provided via environment variables instead. For example, in docker compose pass the environment variables `WG_CMD=sudo wg` and `WG_QUICK_CMD=sudo wg-quick`.

Nice work, I'd also like to see this get merged.

**Comment by BrainStone** [comment]
I don't think it makes sense to abstract it to that level. At least with the intentions of my PR.

**Comment by WeeJeWel** [comment]
Why is this better? It runs inside a Docker container.

**Comment by BrainStone** [comment]
> Why is this better? It runs inside a Docker container.

What if it doesn't? Just because a docker container exists, doesn't mean it shouldn't be able to be ran directly.

Additionally it's an unnecessary security risk to run containers with a root user inside. Always go with least priviledges.

**Pull request closed without merging**
