### PR TITLE
Feat: IPv6

### PR DESCRIPTION
**Pull request by kaaax0815**
## Description

Support IPv6

## Motivation and Context

People should be able to access IPv6.
Replaced `ip` with better and newer tools (that support typescript
This also fixes some other minor things

## How has this been tested?

TODO

## Screenshots (if appropriate):
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kelke** [comment]
So happy to see IPv6 finally implemented 🎉
I don't see any changes to the README, Is there any documentation coming as well?

**Comment by kaumudpa** [comment]
@kaaax0815 I still have issue while using feat-ui branch. Even tough my server is dual stack and my wg-easy container does have both ipv6 & ipv4 - when clients is connected to this server external ip address of the client is always ipv4 and never ipv4.

**Comment by Minionguyjpro** [comment]
> can the PR be tested somehow? Is it present in the development tag? I am not quite sure if it last got built against master or feat-ui.
> 
> I would like to try out the changes and see, if I can spot any problems

I'm wondering the same thing, otherwise I can build it off the branch myself.

**Comment by kaaax0815** [comment]
If you want to test it use the development Tag which is built off of feat-ui

**Comment by Minionguyjpro** [comment]
> If you want to test it use the development Tag which is built off of feat-ui

What are the default credentials for this? I don't seem to be able to find them anywhere nor in the docs...

**Comment by kaaax0815** [comment]
There are no default credentials. You set them through the web setup process

**Comment by Minionguyjpro** [comment]
> There are no default credentials. You set them through the web setup process

Hmm, when I import my old config then it refuses to use the credentials.

**Comment by kaaax0815** [comment]
You should look in the console. Where it should print out an error saying to remove it.

**Comment by Minionguyjpro** [comment]
> You should look in the console. Where it should print out an error saying to remove it.



> You should look in the console. Where it should print out an error saying to remove it.

I've looked but nothing to see. After I uploaded my old .json file, it says the setup finished and wants me to login, but however the password is stored there in the database file and with the stable version it is stored using a variable, so this conflicts but also since there is a username here.

I think some conflict somewhere causes this, but I'm not sure what it is.

**Comment by kaaax0815** [comment]
Please try again with the latest :development tag

**Comment by Minionguyjpro** [comment]
> Please try again with the latest :development tag. you can remove all environment variables as none are required anymore

Now after importing and registering it keeps on loading at the clients page, it gives a HTTP error 500 with /api/client and the container returns the following error:

```
wg-easy  | [nuxt] [request error] [unhandled] [500] Command failed: wg show wg0 dump
wg-easy  | Unable to access interface: No such device
```

**Comment by kaaax0815** [comment]
are there no other errors? as an error should occur when trying to start WireGuard (as its not started apparently)

**Pull request merged**
