### PR TITLE
add allowed IPs to client creation

### PR DESCRIPTION
**Pull request by dcalvo**
This PR adds the functionality described in #243. I needed this for my own use and it was easy enough to share. I added an additional text box to the Create Client window, the value of which is forwarded to the `CreateClient` route. 

I tweaked template generation to make this work, and also slightly changed the next IP calculation to make it more robust in certain situations (i.e. detecting `10.8.0.5/32, 10.8.0.6/32, 10.8.0.7/32` as three occupied IPs).

Vue is not my strong suit so please feel free to redesign as you wish.

### CODE REVIEW

**Comment by t-oster** [comment]
Hi, I also need this exact feature, so I hope it will be merged soon.

**Comment by t-oster** [comment]
for those who cannot wait and only need to adjust a few Allowed-IPS: You can just edit the "address" field of the wg0.json. Just make sure it ends with the current IP address without the "/24".

**Comment by st0nedB** [comment]
> for those who cannot wait and only need to adjust a few Allowed-IPS: You can just edit the "address" field of the wg0.json. Just make sure it ends with the current IP address without the "/24".

Thanks @t-oster , worked for me :)

For anyone who is also a Wireguard n00b like me:
The file is located inside the wg-easy container at `/etc/wireguard/wg0.json`
I used `docker exec -it wg-easy /bin/bash` to get into the container, then edited the file with `vi`.

For example, to add `10.10.0.10/32` as an `AllowedIP`:
`"address": "10.8.0.2",` -> `"address": "10.10.0.10/32,10.8.0.2",`
After restarting the container, `wg show` lists the desired `AllowedIPs` and the routes have been set properly.

Looking forward to see the PR merged. This is indeed a useful feature.

**Comment by centralhardware** [comment]
any updates?

**Comment by pheiduck** [comment]
@dcalvo please rebase your PR from current upstream state.

**Comment by dcalvo** [comment]
@pheiduck Rebased. Please take a look and test if you can. I no longer have the hardware I had when creating this PR, so I can't test it myself to make sure it still works.

**Comment by peterlewis** [comment]
I am going to merge this into a separate branch, so we can have a play with it from there... :)

**Pull request merged**
