### PR TITLE
update ipv6 support v2

### PR DESCRIPTION
**Pull request by kaaax0815**
updates #1108

### CODE REVIEW

**Comment by kaaax0815** [comment]
Most of the functions were already added in my original pr but were later removed likely by a force push or bad merge

**Comment by kaaax0815** [comment]
typescript and #926 would have catched the regression which shouldn't have happened

**Comment by trmdi** [comment]
Does this PR keep the existing conf?

**Comment by trmdi** [comment]
Also, if some people want to disable ipv6, does this PR handle that case?

**Comment by kaaax0815** [comment]
> Does this PR keep the existing conf?

not 100% sure but i think not.

**Comment by trmdi** [comment]
> > Does this PR keep the existing conf?
> 
> not 100% sure but i think not.

Then the old question, since the new conf is just the old one plus new ipv6 addresses, why can't we just add them instead of resetting everything?

**Pull request merged**
