### PR TITLE
IPv6 support

### PR DESCRIPTION
**Pull request by pheiduck**
IPv6 Support thanks to @crazyracer98
Close: #138

### CODE REVIEW

**Comment by pheiduck** [comment]
this could be a problem on some systemes:
@peterlewis @crazyracer98 
```
#25 0.642 ERROR: unable to select packages:
#25 0.644   ip6tables-legacy (no such package):
#25 0.644     required by: world[ip6tables-legacy]
```

**Comment by Jie2GG** [comment]
Can enable docker IPv6 NAT and  nginx proxy wg-easy WebUI support IPv4 + IPv6?#138

**Comment by pheiduck** [comment]
@Jie2GG I think implementing Nginx Proxy doesn't make much sense because many users already use wg-easy behind a proxy and these setups are very different.

**Comment by Jie2GG** [comment]
> @Jie2GG I think implementing Nginx Proxy doesn't make much sense because many users already use wg-easy behind a proxy and these setups are very different.

Yes, nginx proxy is optional. merely furnish SSL and WebUI IPv6 support. wireguard itself supoort IPv6 tun. I'm neet to use IPv6 WebUI, so use nginx proxy.

**Comment by peterlewis** [comment]
> this could be a problem on some systems:
> 
> @peterlewis @crazyracer98 
> 
> ```
> 
> #25 0.642 ERROR: unable to select packages:
> 
> #25 0.644   ip6tables-legacy (no such package):
> 
> #25 0.644     required by: world[ip6tables-legacy]
> 
> ```

Yes, sorry, probably wrong package. I was contributing on the go, so need to just check on Alpine.

**Comment by erik921** [comment]
Just thinking out loud here so I might be wrong, but could it be that the ip6tables-legacy package can be removed as ip6tables-legacy is part of the  ip6tables package.

https://pkgs.alpinelinux.org/contents?branch=v3.12&name=ip6tables&arch=x86_64&repo=main

image

**Comment by peterlewis** [comment]
Thank you, @erik921 for highlighting that!

**Comment by pheiduck** [comment]
```
Docker requires network_mode be set to host in order to access the IPv6 public address.
```

**Comment by kapil-tftus** [comment]
Can we see this anytime soon ipv6 support ? we really need this

**Pull request closed without merging**
