### PR TITLE
Remove redundant newline char in generated client configuration

### PR DESCRIPTION
**Pull request by minghongx**
image

### CODE REVIEW

**Comment by pheiduck** [comment]
@minghongx is this piece of code tested?

**Review by peterlewis — CHANGES_REQUESTED** [review]
I really appreciate your attention to detail, but this feels messy, given it's intended to simply resolve a single redundant newline. I think further thought and review is needed before merging this.

**Comment by minghongx** [comment]
@pheiduck @peterlewis 
I fixed a syntax error. Please find below the test result.

swappy-20240131_064950

**Comment by minghongx** [comment]
> I really appreciate your attention to detail and thank you for your PR, but this feels messy, especially given it's intended to resolve a single redundant newline. I think further thought and review is needed before merging this.

I suspect that this text was generated by a language model. This makes me feel somewhat uncomfortable.

**Comment by peterlewis** [comment]
> > I really appreciate your attention to detail and thank you for your PR, but this feels messy, especially given it's intended to resolve a single redundant newline. I think further thought and review is needed before merging this.
> 
> I suspect that this text was generated by a language model. This makes me feel somewhat uncomfortable.

Nope, sorry to disappoint, that's just how I speak.

**Comment by minghongx** [comment]
@peterlewis 
Apologise for the mistaken suspicion. If you could take another look at the changelog, this PR only makes minor modifications in three places and does not adds complexity.

**Comment by peterlewis** [comment]
Ah yes you're right, thank you. Your updated PR has removed the complexity. Will review and test tomorrow morning. Thanks!

**Comment by pheiduck** [comment]
> @pheiduck @peterlewis I fixed a syntax error. Please find below the test result.
> 
> swappy-20240131_064950

Okay, thanks for your PR, I got what you want to fix here.

**Comment by pheiduck** [comment]
But this will only apply if you create new clients, so users have to recreate there config files if they want to have the new formating.

**Review by pheiduck — APPROVED** [review]

**Comment by pheiduck** [comment]
will be merge if @peterlewis approve as well.

**Comment by peterlewis** [comment]
Looks good, tests good, thanks @minghongx!

**Pull request merged**
