### PR TITLE
add allowed IPs to client creation (part 2)

### PR DESCRIPTION
**Pull request by peterlewis**
To continue the sterling efforts of @dcalvo in https://github.com/wg-easy/wg-easy/pull/313, I have merged to a separate branch, so it's easier to spin-up development builds. If you can please rebase against https://github.com/wg-easy/wg-easy/tree/allowed-ips then that'd be lush!

### CODE REVIEW

**Comment by peterlewis** [comment]
A few issues outstanding that I can see:

- At the moment [we're setting Allowed IPs to the client address](https://github.com/wg-easy/wg-easy/blob/c849d5b52235c39076b6fd6d93e3e010185ff0e9/src/lib/WireGuard.js#L114). This feels like an error, to me, as it results in the AllowedIPs appearing in the Address value in the downloaded `.conf`
- [ ] CSS styling of the 'Allowed IPs'
- [ ] Failing Lint
- [ ] I know it says '(Optional)' but it would be good to have this hidden behind a contrasting 'Advanced' button, to the left of 'Cancel'

**Comment by peterlewis** [comment]
Oops! Renaming branch closed this. Fixing that!

**Comment by peterlewis** [comment]
Hey @ghTravis, join us over here...

**Comment by TheSamDickey** [comment]
Hi!  I have been using wg-easy for years now and just now needed this feature. I traced through the issues up to this, which seems like the latest update.  Are there plans to merge this in soon, or any workarounds until then?  Seems like a wild coincidence I need this feature and it seems to be actively under development haha.

**Pull request closed without merging**
