### PR TITLE
Support for semantic versioning

### PR DESCRIPTION
**Pull request by pheiduck**
https://semver.org/

### CODE REVIEW

**Comment by pheiduck** [comment]
hm, when the build is published, the ".1" is cut off :/

**Comment by pheiduck** [comment]
@peterlewis I think we could change that a little in a different way:
Release: "10"
version: "10.1"

so that relase always uses the major version and the version is changed when patches are applied?
What do you think?

**Comment by pheiduck** [comment]
And doring this playaround tag 10 got updated what should not be happen...
I rebuild latest on production again

**Comment by peterlewis** [comment]
> so that relase always uses the major version and the version is changed when patches are applied? What do you think?

Ideally we want to be tagging both, so the latest (next) release would have `latest`, `10` and `10.1`. However, it`s worth noting that the current release will not have the necessary code to pass the minor version. It`s therefore my understanding that in order to achieve this we would need to go to v11 and then be able to release minor version releases from there-on-in.

**Comment by pheiduck** [comment]
Okay, then we should go to v11 with the upcoming pr #782

**Comment by kaaax0815** [comment]
@pheiduck please consider implementing this. to current version scheme doesnt transfer any information

**Pull request closed without merging**
