### PR TITLE
feat: firewall

### PR DESCRIPTION
**Pull request by tetuaoro**
**IMPORTANT : MAYBE CREATE A NEW BRANCH FOR THIS FEATURE to avoid confusion in issues tab because I don't update the README and because it needs a lot of feedbacks**

### Description

This PR introduces new features for managing firewall rules and retrieving network interface details through the UI. The main features include :

1. **Add Rule** : Allows admins to add firewall rules by specifying source, destination, protocol, and target (ACCEPT or DROP)
2. **Delete Rule** : Provides functionality to delete firewall rules
3. **Get Interfaces** : Retrieves and displays the names and IPv4/IPv6 addresses of all network interfaces.

These enhancements will greatly improve the admin experience by enabling easier management of firewall rules and providing detailed interface information directly from the UI. [task](https://github.com/wg-easy/wg-easy/discussions/1179#discussioncomment-10084528)

### Usage

I often find myself editing the `WG_POST_UP` variable to manage firewall rules, and it can be quite tedious. The PR, allowing you *(and I)* for easier and more efficient configuration. Here are a few practical examples of how these features can be used :
- allow SSH access to the host machine only from specific client IP addresses, enhancing security by blocking unauthorized attempts
- allow only certain clients to access specific services hosted on the machine *(or in my case, containers)*, such as a web server, dns service or database, while blocking others
- prevent clients from pinging each other, reducing the likelihood of certain types of network-based attacks and enhancing privacy.

These examples illustrate how the new firewall management features can be utilized to secure and control network traffic effectively. By using the web interface to configure these rules, you can easily manage network access and security without the need to manually edit variables like `WG_POST_UP` each time.

### Limitation

Currently, the only supported `iptables` command format for adding rules is :
```bash
# CHAIN is default, CIDR & PORT are optional and IPv4, PROTOCOL & TARGET are required
iptables -A CHAIN -s [IPv4 | IPv4/CIDR] -d [IPv4 | IPv4/CIDR] \
  -p PROTOCOL \
  [--sport PORT] [--dport PORT] -j TARGET
```
*Source & Destination supported format* :
- 192.168.1.1
- 192.168.1.1:53
- 192.168.1.0/24
- 192.168.1.0/24:53

### Changes

- added support for managing firewall rules through the UI
- introduced a new file in `WG_PATH` called `fw.rules` to save firewall rules.

image

### CODE REVIEW

**Comment by pheiduck** [comment]
Will take a review, when we have released Version 14.

**Comment by tetuaoro** [comment]
> adding a firewall inside a docker container doesnt much that much sense imo. making a streamlined purpose built ui for that makes more sense. not a generic firewall ui

Yes, I'm agree. I'm using a simple `iptables` command and edit `WG_POST_UP` all the time I'm adding new client. But I'm proposing this firewall feature for all wg-easy admins. It makes more sense to build it in a way that accommodates a variety of use cases and benefits as many people as possible.

**Comment by tetuaoro** [comment]
> I think of wg-easy more like a simple vpn solution rather than an complex enterprise solution. with e.g. editing a ip address of the client the user would also have to change the firewall rules. but with ui built for specific solution the rules could be automatically changed

Hey man, you’ve given me a great idea for a future PR : reserving a range of IPs for clients *(or services)*. Thx

**Comment by tetuaoro** [comment]
> should wait for #1228 and be implemented in the same style

menu FIrewall ? that's make sense haha

**Comment by tetuaoro** [comment]
Waiting for #1244

**Pull request closed without merging**
