### PR TITLE
refactor: import & export configuration

### PR DESCRIPTION
**Pull request by pheiduck**
@tetuaoro you can test here, all your code need to land into imexport.
If needs some more fixes

### CODE REVIEW

**Comment by pheiduck** [comment]
Test image: `ghcr.io/wg-easy/wg-easy:development`

Let me know for a rebuild.

**Comment by pheiduck** [comment]
Tested worked on my side now!

**Comment by tetuaoro** [comment]
> Tested worked on my side now! @tetuaoro could you improve the position of the icons? at the same line like the "+" for New and the buttons as well not centered. grafik

Ah ok, good to hear it's working on your side. I'll fix the icons and buttons.

**Comment by tetuaoro** [comment]
Oula, Idk how to push there. Should I open a new pr ?

**Comment by pheiduck** [comment]
@tetuaoro I would also suggest to use icons from here: https://heroicons.com/

**Comment by tetuaoro** [comment]
> @tetuaoro I would also suggest to use icons from here: https://heroicons.com/

Oh, I didn't know about that website. I'll check it out this afternoon.

**Pull request merged**
