### PR TITLE
refactor: don't use the layouts folder

### PR DESCRIPTION
**Pull request by cany748**
## Description
I moved the Header and Footer to the components/Layout folder, in order to use them as normal components.

## Motivation and Context
This change is necessary to prevent misuse of Nuxt tools.
Documentation link: https://nuxt.com/docs/guide/directory-structure/layouts
Usage examples from the Nuxt team: https://github.com/nuxt-ui-pro/saas/tree/main/app/layouts
https://github.com/nuxt-ui-pro/saas/tree/main/app/components

## How has this been tested?
This has been tested.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cany748** [comment]
why do you even need to use layouts? what's the point? you want this code to execute every time without doing anything useful? https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/components/nuxt-layout.ts

**Comment by kaaax0815** [comment]
There is a reason why the Layouts feature exists. Then it should be used. Optimizing for miniscule performance improvements doesn't make sense, if it adds logical separation

**Comment by cany748** [comment]
I didn't say that the Layouts feature is not needed. what I'm trying to say is that the Layouts feature is now not needed in this application. you should use component names for logical separation.

**Comment by tetuaoro** [comment]
I'll introduce multiple routes like `/` (index), `/dashboard` and `/dashboard/settings`. Maybe an `AppHeader` should be a component and `Footer` should remain a layout... imo.

**Comment by kaaax0815** [comment]
I'll close this pr for now. Will take it into consideration. Feel free to reopen if the new ui is more polished and all ideas are clear

**Pull request closed without merging**
