### PR TITLE
Feat: Migrations

### PR DESCRIPTION
**Pull request by kaaax0815**
## Description

Adds Migration functionality to database

## Motivation and Context

Adding new features with a database is not that easy

## How has this been tested?

Locally

## Screenshots (if appropriate):
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kaaax0815** [comment]
@tetuaoro Request review

**Review by tetuaoro — APPROVED** [review]
Better ! Now, `System` is not null.

**Comment by tetuaoro** [comment]
> Adding new features with a database is not that easy

Haha yeah

**Comment by kaaax0815** [comment]
@tetuaoro When do you think you will be able to rewrite Wireguard?

**Comment by tetuaoro** [comment]
> @tetuaoro When do you think you will be able to rewrite Wireguard?

Friday, I'm busy this week

**Comment by kaaax0815** [comment]
> Friday, I'm busy this week

Ok. If I have some time I'll start

**Pull request merged**
