### PR TITLE
feat: PASSWORD_HASH helpers 

### PR DESCRIPTION
**Pull request by tetuaoro**
## Description
This pull request introduces enhancements aimed at improving password security and usability within the wg-easy project.

### Changes

1. **Dynamic PASSWORD_HASH Generation** :
Implemented functionality to generate PASSWORD_HASH using a binary built from the wg-password directory. This approach replaces the static plain text PASSWORD environment variable, providing increased security by dynamically generating bcrypt hashes.

2. **Updated README** :
Enhanced the README with detailed instructions on using Docker to generate bcrypt hashes. Added steps guide for generating bcrypt hashes from the command line, ensuring clear guidelines for PASSWORD_HASH generation.

3. **Updated Server Function** :
Removed PASSWORD environment variable. We don't need it anymore.

### Using Docker to generate PASSWORD_HASH on the fly

To generate a bcrypt hash using wg-easy :

```bash
docker run ghcr.io/wg-easy/wg-easy wgpw YOUR_PASSWORD
```

Copy the entire output and run a container with environment :

```bash
docker run ... --env PASSWORD_HASH='$2d$12...' ghcr.io/wg-easy/wg-easy
```

Make sure to enclose your password in single quote. More details in wg-easy/wg-password/PASSWORD.md file.

## Future Improvement

In the future, I plan to integrate a feature that allows users to change their passwords directly from the website, enhancing user convenience and security. In fact I just need it.

### CODE REVIEW

**Comment by tetuaoro** [comment]
I checked the failing build, maybe the manifest file is on your side.

**Comment by pheiduck** [comment]
> I checked the failing build, maybe the manifest file is on your side.

rust docker image is only available for amd64 and arm64 so the armv6/7 is not solved due this issues.

**Comment by tetuaoro** [comment]
I'm waiting for his response. If he doesn't want, I'll rewrite in javascript. Have a nice wk-end.

**Comment by pheiduck** [comment]
Sorry for delay, I am a bit busy until now, but it's on my list.

**Comment by pheiduck** [comment]
We may should cross-compile: https://rust-lang.github.io/rustup/cross-compilation.html

**Comment by tetuaoro** [comment]
> We may should cross-compile: https://rust-lang.github.io/rustup/cross-compilation.html

Hum..I'll rewrite to js. It's just to help users to make a password hash.

**Comment by pheiduck** [comment]
> > We may should cross-compile: https://rust-lang.github.io/rustup/cross-compilation.html
> 
> Hum..I'll rewrite to js. It's just to help users to make a password hash.

Your changes also make the Python script obsolete, as it does the same thing as this one.

**Comment by tetuaoro** [comment]
after thinking it is better to have more maintainable code

**Review by pheiduck — APPROVED** [review]

**Comment by pheiduck** [comment]
@tetuaoro is it ready to merge?

**Comment by tetuaoro** [comment]
> @tetuaoro is it ready to merge?

yes, it is.

**Pull request merged**
