### PR TITLE
Update to current NodeJs, wireguard v1.0.20210914

### PR DESCRIPTION
**Pull request by comassky**
Tested with Ubuntu 20.04.3

Update wireguard : 1.0.20200102 -> 1.0.20210914

### CODE REVIEW

**Comment by ffoxin** [comment]
Why did you remove sha1 hash? Isn't it less secure?

**Comment by comassky** [comment]
@ffoxin 

You are right, I just added them

**Comment by smartpierre** [comment]
I there a way to quickly merge the security fixes ? Is @WeeJeWel the only person that can approve the PR on this repository ?

**Comment by comassky** [comment]
I have the same issue with another project, the solution is to switch to non alpine image.

Maybe create an Pi image (from node non alpine), tagged with wg-easy:pi

And an other image (tagged latest) with my pull request ?

**Comment by ShlomiD83** [comment]
> Raspberry Pi crashes on newer alpine images: https://github.com/athombv/node-homey/blob/master/lib/App.js#L614

I've cloned the repo and built the image using :node:17-alpine@sha256:0e83c810225bc29e614189acf3d6419e3c09881cefb9f7a170fdcfe3e15bbfd5 and nothing crashed.
Pi is still working and so is Wireguard.

**Comment by ad84** [comment]
> > Raspberry Pi crashes on newer alpine images: https://github.com/athombv/node-homey/blob/master/lib/App.js#L614
> 
> I've cloned the repo and built the image using :node:17-alpine@sha256:0e83c810225bc29e614189acf3d6419e3c09881cefb9f7a170fdcfe3e15bbfd5 and nothing crashed. Pi is still working and so is Wireguard.

I've recently done the same with the image node:16-alpine on a raspberry pi 4 running x64 Debian 11. It's been fine, no crashes from wiregaurd or the pi.

**Comment by ShlomiD83** [comment]
> > > Raspberry Pi crashes on newer alpine images: https://github.com/athombv/node-homey/blob/master/lib/App.js#L614
> > 
> > 
> > I've cloned the repo and built the image using :node:17-alpine@sha256:0e83c810225bc29e614189acf3d6419e3c09881cefb9f7a170fdcfe3e15bbfd5 and nothing crashed. Pi is still working and so is Wireguard.
> 
> I've recently done the same with the image node:16-alpine on a raspberry pi 4 running x64 Debian 11. It's been fine, no crashes from wiregaurd or the pi.

Tried with 18.1 but keep getting manifest error when building the image.
Maybe my sha256 is incorrect.

**Comment by WeeJeWel** [comment]
This will break most Raspberry Pi installations.

**Comment by ShlomiD83** [comment]
@WeeJeWel can wireguard-tools be updated without nodejs update?

**Comment by WeeJeWel** [comment]
Yes they have just been updated.

**Comment by ShlomiD83** [comment]
> Yes they have just been updated.

Hey, I still don't see the updated version.
Was this included in the latest release?

**Comment by ShlomiD83** [comment]
@comassky why did you remove the sha hash?

**Comment by comassky** [comment]
> @comassky why did you remove the sha hash?

Bad manipulation ! Fixed

**Comment by ShlomiD83** [comment]
> > @comassky why did you remove the sha hash?
> 
> Bad manipulation ! Fixed

can't seem to build the image after editing the Dockerfile.

"Step 4/14 : RUN npm ci --production
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in bcd609268426
exec /bin/sh: exec format error
The command '/bin/sh -c npm ci --production' returned a non-zero code: 1"

**Comment by comassky** [comment]
> The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Maybe try to remove node_modules folder and build again.

**Comment by ShlomiD83** [comment]
> > The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> 
> Maybe try to remove node_modules folder and build again.

I've managed to update node to the latest version (18.6) and everything is working as it should (both WG & RPi)

**Comment by comassky** [comment]
Updated to latest Node 18 (alpine based).
Update some libraries of packages.json (tested, everything is working)

**Comment by ditek** [comment]
I created this image based on @comassky's work and it's working fine on my RPi 2 setup. Hope someone can find it useful.
https://hub.docker.com/repository/docker/ditek/wg-easy

**Comment by peterlewis** [comment]
All good in the hood, on the "keeping node updated" front, now. Thank you for your PR! 👍🏻

**Pull request closed without merging**
