### PR TITLE
Create possibility to manage multiple users

### PR DESCRIPTION
**Pull request by fvalle1**
At [Elemento](https://github.com/Elemento-Modular-Cloud) we (especially [flavi012](https://github.com/flavi012)) worked to integrate the possibility to manage multiple users.

We added:
- multiple user
- possibility to change password 
- redid to store data

### CODE REVIEW

**Comment by WeeJeWel** [comment]
It's better to put another auth project in front of wg-easy for multiple user management.

One tool, one job.

**Comment by fvalle1** [comment]
wg-easy has an authentication itself and it provides the possibility to create multiple clients, so it already has auth features. Even before my PR it is not *one tool one job*

It would be much more useful to have the possibility in which multiple admins (all the IT admins) can manage the company clients.

Think about it, or remove all the auth features from wg-easy, having limited auth features is useless.

**Comment by WeeJeWel** [comment]
I'd love to, but for most users a single password is fine :)

**Comment by fvalle1** [comment]
My PR is not intended for them ;)



Filippo Valle, Ph.D.
CTO
Elemento s.r.l.
📱+39 3274892927
***@***.***
🌐 https://elemento.cloud

**Comment by WeeJeWel** [comment]
This repo is, though. Feel free to publish your fork :)

**Pull request closed without merging**
