### PR TITLE
deploy-nightly.yml: Release number is not provieded

### PR DESCRIPTION
**Pull request by pheiduck**
Remove unused: `Set environment variables` Step on deploy-nightly CI

### CODE REVIEW

**Comment by peterlewis** [comment]
Sorry, this was an intentional tweak as we haven't-yet internally established versioning process when developing on nightlies. It felt, therefore I felt that `nightly` was simply `nightly`, as opposed to being version-specific.

**Comment by peterlewis** [comment]
Oh! Doh! Sorry, you're tidying up! I really didn't look closely enough at this! Sorry!

**Comment by pheiduck** [comment]
@peterlewis I am not sure if it is relevant to assign a version number for nightly builds. As many of the users will use the `nightly` tag on there docker-compose

**Comment by peterlewis** [comment]
> @peterlewis I am not sure if it is relevant to assign a version number for nightly builds. As many of the users will use the `nightly` tag on there docker-compose

Yes, I wholly agree. See my edit to my original comment. I was being tremendously lackadaisical in my initial glance over this PR! 😀

**Pull request merged**
