### PR TITLE
fix backward compatibility issue

### LINKED ISSUE #140: Add support for non-/24 subnets
As of now you can only specify /24 subnets in WG_DEFAULT_ADDRESS. 254 IP addresses are insufficient for my use case.

It would be better to allow users to specify the subnet not in "192.168.0.x" format, but in "192.168.0.0/24" format, allowing for more flexibility.

### LINKED ISSUE #922: More than 255 clients
Hello and thank you for this package.

How to create support for more than **255** clients?

### LINKED ISSUE #943: Backwards compatibility issue with `WG_DEFAULT_ADDRESS`
In latest nightly, on setups where `WG_DEFAULT_ADDRESS` is set in the current format (e.g. `172.16.2.x`) the container fails to start with error advising of invalid IP address.

It is _essential_ that clients should not break on upgrade as a result of any changes to variables.

@pheiduck

### PR DESCRIPTION
**Pull request by pheiduck**
Fixes #943
Closes #140 
Closes #922 
Thank you @utkarsh867

### CODE REVIEW

**Comment by pheiduck** [comment]
it's not fixing the issue at all:
```
 module.exports.WG_DEFAULT_ADDRESS = process.env.WG_DEFAULT_ADDRESS.repla   │
│   ce('x', '0') || '10.8.0.0';                                                │
│                                                                      ^       │
│   2024-03-27T13:39:58.376205588Z                                             │
│   TypeError: Cannot read properties of undefined (reading 'replace')         │
│       at Object.<anonymous> (/app/config.js:17:68)                           │
│       at Module._compile (node:internal/modules/cjs/loader:1356:14)          │
│       at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)   │
│       at Module.load (node:internal/modules/cjs/loader:1197:32)              │
│       at Module._load (node:internal/modules/cjs/loader:1013:12)             │
│       at Module.require (node:internal/modules/cjs/loader:1225:19)           │
│       at require (node:internal/modules/helpers:177:18)                      │
│       at Object.<anonymous> (/app/lib/WireGuard.js:30:5)                     │
│       at Module._compile (node:internal/modules/cjs/loader:1356:14)          │
│       at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)   │
│   2024-03-27T13:39:58.376485269Z                                             │
│   Node.js v18.19.1
```

**Comment by utkarsh867** [comment]
> it's not fixing the issue at all:
> 
> ```
>  module.exports.WG_DEFAULT_ADDRESS = process.env.WG_DEFAULT_ADDRESS.repla   │
> │   ce('x', '0') || '10.8.0.0';                                                │
> │                                                                      ^       │
> │   2024-03-27T13:39:58.376205588Z                                             │
> │   TypeError: Cannot read properties of undefined (reading 'replace')         │
> │       at Object.<anonymous> (/app/config.js:17:68)                           │
> │       at Module._compile (node:internal/modules/cjs/loader:1356:14)          │
> │       at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)   │
> │       at Module.load (node:internal/modules/cjs/loader:1197:32)              │
> │       at Module._load (node:internal/modules/cjs/loader:1013:12)             │
> │       at Module.require (node:internal/modules/cjs/loader:1225:19)           │
> │       at require (node:internal/modules/helpers:177:18)                      │
> │       at Object.<anonymous> (/app/lib/WireGuard.js:30:5)                     │
> │       at Module._compile (node:internal/modules/cjs/loader:1356:14)          │
> │       at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)   │
> │   2024-03-27T13:39:58.376485269Z                                             │
> │   Node.js v18.19.1
> ```

that is strange. I did test it.

**Comment by utkarsh867** [comment]
Ah I see! In the case that `WG_DEFAULT_ADDRESS` is not defined, things break. oversight on my part. I can help solve this.

**Comment by pheiduck** [comment]
I have `- WG_DEFAULT_ADDRESS_IPV4=10.8.0.x`

**Comment by utkarsh867** [comment]
`WG_DEFAULT_ADDRESS_IPV4` is a valid configuration?

`WG_DEFAULT_ADDRESS` works on my end.

image

image

And I can connect to the VPN as well.

**Comment by pheiduck** [comment]
> WG_DEFAULT_ADDRESS_IPV4 is a valid configuration?

Yep, was from a diffrent fork I guess.
Works with `WG_DEFAULT_ADDRESS` also latest/12 works with that.

**Pull request merged**
