### PR TITLE
feat: no private key

### PR DESCRIPTION
**Pull request by pheiduck**
Patch by @willtho89

### CODE REVIEW

**Comment by pheiduck** [comment]
sorry to bother you @willtho89 it needs rebase up on `master` wasn't able to :/

**Comment by pheiduck** [comment]
Otherwise we can merge it as it is...
We should wait until @peterlewis approve it.

**Review by peterlewis — APPROVED** [review]
Looks good, thank you!

**Comment by pheiduck** [comment]
@willtho89 great news works on my side as well.

**Pull request merged**
