### PR TITLE
 add multilanguage support

### PR DESCRIPTION
**Pull request by pheiduck**
add multilanguage support and add russian language (https://github.com/wg-easy/wg-easy/pull/278) from cany748

### CODE REVIEW

**Comment by pheiduck** [comment]
@cany748 please test: `ghcr.io/wg-easy/wg-easy:development`

**Comment by cany748** [comment]
> @cany748пожалуйста, проверьте:`ghcr.io/wg-easy/wg-easy:development`

It looks cool!

**Comment by pheiduck** [comment]
> > @cany748пожалуйста, проверьте:`ghcr.io/wg-easy/wg-easy:development`
> 
> It looks cool!

I am testing it as well but I can change the Language.
How can I do this on the docker compose file?

**Comment by babico** [comment]
> > > @cany748пожалуйста, проверьте:`ghcr.io/wg-easy/wg-easy:development`
> > 
> > 
> > It looks cool!
> 
> I am testing it as well but I can't change the Language. How can I do this on the docker compose file?

Untitled
you can change language with this way

**Comment by babico** [comment]
> > > @cany748пожалуйста, проверьте:`ghcr.io/wg-easy/wg-easy:development`
> > 
> > 
> > It looks cool!
> 
> I am testing it as well but I can't change the Language. How can I do this on the docker compose file?

image
you can change with this way

**Comment by cany748** [comment]
> > > @cany748пожалуйста, проверьте:`ghcr.io/wg-easy/wg-easy:development`
> > 
> > 
> > It looks cool!
> 
> I am testing it as well but I can't change the Language. How can I do this on the docker compose file?

```
  wireguard:
    depends_on: [adguardhome]
    image: ghcr.io/wg-easy/wg-easy:development
    container_name: wireguard
    environment:
      - LANG=de
```

**Comment by pheiduck** [comment]
Yep, Thanks it's working. Great job! @cany748 
I will update the README and docker-compose files as well.

**Review by peterlewis — APPROVED** [review]
This is an excellent improvement, thank you, all!

**Pull request merged**
