### PR TITLE
Show total RX/TX data for each client in UI

### PR DESCRIPTION
**Pull request by suxscribe**
As discussed in #184 

**Changes:**
- Moved RX and TX into separate columns and highlighted the values. Added Total RX / TX values below.
- Added wrapping of controls and RX / TX blocks on tablet and mobile
- Added UI_DETAILED_STATS variable to enable new UI 

**Layout screenshots:**

<details>
  <summary>Desktop view</summary>

  desktop

</details>

<details>
  <summary>Tablet view</summary>

  tablet

</details>

<details>
  <summary>Mobile view</summary>

  mobile

</details>

### CODE REVIEW

**Comment by pheiduck** [comment]
@suxscribe please fix lint errors

**Comment by suxscribe** [comment]
@pheiduck 👌fixed

**Comment by pheiduck** [comment]
@suxscribe thanks for fixing lint errors. Could you please update docker-compose and the readme how to toggle this feature on/off?

**Comment by suxscribe** [comment]
@pheiduck Added feature description, please check

**Comment by peterlewis** [comment]
@suxscribe Starting testing now. I note that when client is first created it shows as being created `54 years ago` (years since 1970). This needs to be blank for unseen clients.

**Comment by peterlewis** [comment]
@suxscribe I would suggest that it would look better for, when space allows, the stats to appear in-line with the client information (with the same padding on the RHS), with the buttons underneath.

stats

**Comment by peterlewis** [comment]
@suxscribe And thank you, btw! :) Sorry, have realised my feedback lacks the deserved platitude!

**Comment by suxscribe** [comment]
@peterlewis 

> I note that when client is first created (or when container is rebooted) it shows as being created 54 years ago

oops, forgot to bring it back after debugging

> I would suggest that it would look better for, when space allows, the stats to appear in-line with the client information (with the same padding on the RHS), with the buttons underneath.

Makes sense, I'll look into it

> And thank you, btw! :) Sorry, have realised my feedback lacks the deserved platitudes!

Thanks, it's my pleasure to contribute!

**Pull request merged**
