### PR TITLE
lib/WireGuard.js - ListenPort from ENV

### LINKED ISSUE #602: lib/WireGuard.js - ListenPort is hardcoded as 51820
Greetings, 

First of all, thanks for this great tool. It saved my life today.

Yet, while attempting to use the generated wg0.conf as a volume into a regular apt-intalled WireGuard (because I love your U.I.)
I've noticed this value is not following the docker env:
https://github.com/wg-easy/wg-easy/blob/642d6d62edb95a96e57b704966b65135f4f3ea94/src/lib/WireGuard.js#L98C10-L98C10

I edited the value manually to `${WG_PORT}` and now it works fine.
Please consider editing it so it carries the defined WG_PORT from env.

cheers,

### PR DESCRIPTION
**Pull request by whithil**
this commit fixes #602

### CODE REVIEW

**Comment by pothi** [comment]
As mentioned in [your issue](https://github.com/wg-easy/wg-easy/issues/602), wg-easy listens on port 51820 insider the container. If you are using a non-default UDP port, you have to change it in two places while creating the docker container...

1. The port that exposed to the host
2. The value of WG_PORT

Here's the sample configuration that uses a non-default UDP port of 55555...

```
docker run -d \
  --name=wg-easy \
  -e WG_HOST=🚨YOUR_SERVER_IP \
  -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
  -v ~/.wg-easy:/etc/wireguard \

  -e WG_PORT=55555 \
  -p 55555:51820/udp \

  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy
```

**Comment by DareFox** [comment]
> As mentioned in [your issue](https://github.com/wg-easy/wg-easy/issues/602), wg-easy listens on port 51820 insider the container. If you are using a non-default UDP port, you have to change it in two places while creating the docker container...
> 
>     1. The port that exposed to the host
> 
>     2. The value of WG_PORT
> 
> 
> Here's the sample configuration that uses a non-default UDP port of 55555...
> 
> ```
> docker run -d \
>   --name=wg-easy \
>   -e WG_HOST=🚨YOUR_SERVER_IP \
>   -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
>   -v ~/.wg-easy:/etc/wireguard \
> 
>   -e WG_PORT=55555 \
>   -p 55555:51820/udp \
> 
>   -p 51821:51821/tcp \
>   --cap-add=NET_ADMIN \
>   --cap-add=SYS_MODULE \
>   --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
>   --sysctl="net.ipv4.ip_forward=1" \
>   --restart unless-stopped \
>   weejewel/wg-easy
> ```

Sometimes you need to change internal port too (like having two wireguards servers in same network, like wg-easy + netbird/tailscale), this PR should give solution to this problem

**Comment by peterlewis** [comment]
Just to let you know that [this has been implemented](https://github.com/peterlewis/wg-easy/commit/78ac220852fdd551a85b9efe7d7f7390eac4d360) in the [fork]((https://github.com/peterlewis/wg-easy) I maintain, if it is of interest.

**Comment by peterlewis** [comment]
Thank you, this was merged in https://github.com/wg-easy/wg-easy/commit/6e08e5a824cf3ebe50deb7ca240d74f9cd6c8e4b.

**Pull request closed without merging**
