### PR TITLE
 Replace Express with Koa

### PR DESCRIPTION
**Pull request by pheiduck**
Thanks to @oplexz

### CODE REVIEW

**Comment by pheiduck** [comment]
Still unstable, needs rework

**Comment by pheiduck** [comment]
I reverted the [src/lib/Util.js](https://github.com/wg-easy/wg-easy/pull/794/commits/496821f00a58c11be3d90d05c1a14cd320989358#diff-74167d91a1e54a2ef277091a63baa538bea68d5bd87b6cd9266e3149e58334cb) changes.

**Comment by pheiduck** [comment]
[express](https://github.com/wg-easy/wg-easy/commit/79f1b885343f141ec7eb726236bf9e4d545be7a2) is still under development.

**Comment by cany748** [comment]
Why was the choice made towards Koa, and not Fastify or Nitro (which uses h3)?
Fastify and Nitro have better performance. Nitro also supports Bun and Deno, and is written in Typescript.

**Comment by pheiduck** [comment]
> Why was the choice made towards Koa, and not Fastify or Nitro (which uses h3)? Fastify and Nitro have better performance. Nitro also supports Bun and Deno, and is written in Typescript.
> 
> https://github.com/fastify/benchmarks

@cany748 This PR is still in progress due it's not working in some area of the codebase for e.g. the Session is undefined.
@oplexz had not found a way to get valid session working with that framework.

The Main Product is still using Express.

Feel free to open a PR.

**Comment by peterlewis** [comment]
I'm not hugely confident as to what the right decision is, with regards to migration away from express. I appreciate there is both this PR as well @cany748's PR (#880) and I want to both ensure we're taking it in the best direction, as well as ensuring that we're not wasting your time, too. Would welcome thoughts from all regarding this. Feels like we need to be making an informed choice.

**Comment by pheiduck** [comment]
Poll is here: https://github.com/wg-easy/wg-easy/discussions/890
Please vote.

**Pull request closed without merging**
