### PR TITLE
feat: UI configure password on first startup + database

### PR DESCRIPTION
**Pull request by tetuaoro**
## Description

Removed the (required) `PASSWORD_HASH` environment variable from the docker config. Use the Web UI for handling password and setting up the username and password at first start.

## Motivation and Context

This change simplifies the deployment process and improves user experience. By handling password hashing through the UI, we eliminate the need for setting environment variables, which can be cumbersome and error-prone, and resolve a lot of related issues (#1197, #1235 ...).

## How has this been tested?

Tested by running the application, opening the `Settings` menu and setting your username and password.

### First setup
image

### Settings menu
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tetuaoro** [comment]
Oh you tried a lot, seems arm (v7 is not supported)[https://github.com/TryGhost/node-sqlite3?tab=readme-ov-file#prebuilt-binaries]. My bad

**Comment by pheiduck** [comment]
Yep armv6 too, will revert my changes

**Comment by tetuaoro** [comment]
ok, switch to simple json file hahaha

**Comment by pheiduck** [comment]
We have to find a database to support all our architectures or move on drop these but this is uncool 🙃

**Comment by pheiduck** [comment]
alpine sqlite3 support all architectures.
https://git.alpinelinux.org/aports/tree/main/sqlite/APKBUILD?id=898038f2bb7eae5ebd315cde97cac25c3e66a757
I don't know if these are usable in nodejs.

**Comment by pheiduck** [comment]
Please try this flag: --build-from-source=sqlite3 otherwise everything is build from source. If it possible to reduce the buildtime

**Comment by pheiduck** [comment]
> The password is required and the default password is 'admin'.

This will be a security hole, the Password should be choose by the user.

**Comment by tetuaoro** [comment]
I will use json file until we find a great and supportd database provider.

**Comment by tetuaoro** [comment]
> using a supported database would solve #1216 and would greatly increase dx for new features. maybe adding a db would be great for a separate pr? then things like all the env vars could be configured in the ui
> 
> maybe try https://orm.drizzle.team/docs/get-started-sqlite#better-sqlite3 (drizzle would add good dx and safety) or [`better-sqlite3`](https://www.npmjs.com/package/better-sqlite3) alone. or use drizzle with a e.g. postgres db for better performance
> 
> for the security considerations. other projects generate a random password on first start and store it in a file

Hi & thank you, I'll try next week.

**Comment by tetuaoro** [comment]
Can you refine your idea about the password ? How should we proceed ?

**Comment by tetuaoro** [comment]
> off-topic: really like that you created a database interface to support multiple databases in the future

Yes, I use an abstract class to do this. I read your post #1216. I'll try first if a service in the container would do, like postgres or mysql. I'm talking about weight.

**Comment by tetuaoro** [comment]
> > I'll try first if a service in the container would do, like postgres or mysql. I'm talking about weight.
> 
> no need for a db inside the wg-easy container. if you want to use postgres over sqlite then spin up a new container.

Have you tried `lowdb` (ref #1216) ? It use json file.

**Comment by pheiduck** [comment]
`lowdb` seems more up-to-date

**Comment by tetuaoro** [comment]
> very good work @tetuaoro as the dashboard will/should reuse parts of other ui. maybe #937 is needed to split ui into components

yes, I would like to write components and esm modules.

**Comment by tetuaoro** [comment]
Done.

`PASSWORD_HASH` has been completely deleted. You configure a username and password on first startup (if database does not exist).

**Comment by tetuaoro** [comment]
Waiting for #1244

**Comment by kaaax0815** [comment]
@tetuaoro you can recreate this pr against `feat-ui`

**Pull request closed without merging**
