### PR TITLE
Rebase from pheiduck

### LINKED ISSUE #682: Unable to start WG-easy using v8
**Describe the bug**
When using the latest docker image from ghcr.io/wg-easy/wg-easy I am unable to get the container going. Results with the following issue:

```
2023-12-19T20:12:12.563Z Server Listening on http://0.0.0.0:51821
2023-12-19T20:12:12.565Z WireGuard Loading configuration...
2023-12-19T20:12:12.569Z WireGuard Configuration loaded.
2023-12-19T20:12:12.569Z WireGuard Config saving...
2023-12-19T20:12:12.571Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#]
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument
[#] ip link delete dev wg0
at ChildProcess.exithandler (node:child_process:422:12)
at ChildProcess.emit (node:events:517:28)
at maybeClose (node:internal/child_process:1098:16)
at Socket.<anonymous> (node:internal/child_process:450:11)
at Socket.emit (node:events:517:28)
at Pipe.<anonymous> (node:net:350:12) {
code: 4,
killed: false,
signal: null,
cmd: 'wg-quick up wg0'
}
```

**To Reproduce**
Running the latest image using the suggested docker run or compose setup

Running this on a Synology NAS that already has WG support installed and working (with older container image). Have multiple confirmations from a number of Synology models/users.

Also, manually running wg-quick up wg0 (using the same location of the wg0 file that wgeasy does), in fact successfully starts the wg-crypt-wg0 process. Ofc, running container after that reports the port is already in use. So again, with v7 of wgeasy everything is running smooth, but the latest v8 image is causing issues.

Any assistance would be appreciated. If needed I can post any log, or execute any command as needed.

Thank you in advance!

### PR DESCRIPTION
**Pull request by peterlewis**
This PR merges-in changes from downstream.

Clarifications needed:

- [x] Do we want to be using versioned actions (e.g. `actions/checkout@v4`) or unversioned (e.g. `actions/checkout@main`)
- [x] Similarly to the above, in `lint.xml` is it correct for us to be using `node-version: 'current'`?
- [x] Have simply merged-in `package.json` and `package-lock.json` from downstream, at this time.

To-do:

- [x] Dark mode using `media` instead of `class` toggle
- [x] Move from `iptables` to `iptables-legacy` to fix #682
- [x] ~As it stands, if merged it would require of primary branch from `master` to `main`~ (Resolved through referencing `master`)

### CODE REVIEW

**Review by pheiduck — COMMENTED** [review]
I updated every CI action to be versioned also node-version is now at `18` instead of `current`

**Comment by peterlewis** [comment]
> I updated every CI action to be versioned also node-version is now at `18` instead of `current`

Awesome! Thank you for that! :)

**Comment by peterlewis** [comment]
Whilst I much prefer 'Main', I'd suggest that we reference 'Master' as opposed to renaming primary branch to 'Main' at this time, as doing so could cause moderate disruption downstream. Do you have thoughts on this?

**Comment by peterlewis** [comment]
Holy moly, that's awesome, it "just works"! 😄

**Comment by pheiduck** [comment]
> Whilst I much prefer 'Main', I'd suggest that we reference 'Master' as opposed to renaming primary branch to 'Main' at this time, as doing so could cause moderate disruption downstream. Do you have thoughts on this?

We should stay on `master` until we a ready for rename to `main`.

**Comment by peterlewis** [comment]
> > Whilst I much prefer 'Main', I'd suggest that we reference 'Master' as opposed to renaming primary branch to 'Main' at this time, as doing so could cause moderate disruption downstream. Do you have thoughts on this?
> 
> We should stay on `master` until we a ready for rename to `main`.

Noted and agreed! Spotted [one more](https://github.com/wg-easy/wg-easy/blob/rebase-pheiduck/.github/workflows/npm-update-bot.yml) so have made the change from `main` to `master` there, too.

**Comment by pheiduck** [comment]
> Noted and agreed! Spotted [one more](https://github.com/wg-easy/wg-easy/blob/rebase-pheiduck/.github/workflows/npm-update-bot.yml) so have made the change from `main` to `master` there, too.

Good catch ;)

**Comment by peterlewis** [comment]
What are your thoughts on [this](https://github.com/wg-easy/wg-easy/pull/685/checks?check_run_id=19867777833)?

**Comment by pheiduck** [comment]
> What are your thoughts on [this CodeQL fail](https://github.com/wg-easy/wg-easy/pull/685/checks?check_run_id=19867777833)?

I have not yet found a good solution for this security problem "Missing CSRF middleware".

**Comment by peterlewis** [comment]
In which case. Are we ready to merge? What have we forgotten? 😄

**Comment by pheiduck** [comment]
I think its ready, only the `deploy-stable.yml` does not seem to work.

**Comment by peterlewis** [comment]
I believe that may be because the changes in deploy-stable.yml have not yet made it to production branch? Or am I barking up the wrong tree, there?

**Comment by peterlewis** [comment]
Ah, spotted it. Current stable deployment is called `deploy.yml` which has confused the actions, a wee bit. Have renamed.

**Comment by pheiduck** [comment]
Okaym lets do the merge

**Comment by peterlewis** [comment]
I'll let you do the honours! 🥇 After-all, most of the commits downstream were yours! 😄

**Comment by peterlewis** [comment]
```
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 172.16.2.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 172.16.2.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
/usr/bin/wg-quick: line 295: iptables: command not found
[#] ip link delete dev wg0
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

**Comment by peterlewis** [comment]
going to revert the `iptables-legacy` change for now.

**Comment by pheiduck** [comment]
> going to revert the `iptables-legacy` change for now.

Yep, its not working with `iptables-legacy`

**Pull request merged**
