### PR TITLE
Version 10: Dark mode & sessionless auth

### PR DESCRIPTION
**Pull request by peterlewis**
**Stable Release: 2024-01-10**
Version 10 release, including:

- Fixed issue when running on Synology NAS
- Added sessionless HTTP API auth (with thanks to @James-Stokes)
- Automatic dark mode (with thanks to @goodbyepavlyi)
- Version bumps
- Code refinement (that feels like it's only a small step up from saying "bug fixes")

### CODE REVIEW

**Comment by peterlewis** [comment]
Would be good to get https://github.com/wg-easy/wg-easy/issues/692 addressed, prior to release.

**Comment by peterlewis** [comment]
@James-Stokes Thank you for your PR in https://github.com/wg-easy/wg-easy/pull/586/files

We've rebased from @pheiduck's repository downstream which also aims to introduce sessionless HTTP API authentication, but which is based on @EugeneDoingThings' implementation.

Could I please ask you to review the implementation in this PR and feedback?

Thanks!

Peter :)

**Comment by pheiduck** [comment]
My sessionless HTTP API authentication is based on PR in https://github.com/wg-easy/wg-easy/pull/586/files from @James-Stokes

**Comment by peterlewis** [comment]
Ah excellent! Thank you for clarifying, @pheiduck! Sorry, there were two PRs and I evidently referenced the wrong one!

**Comment by peterlewis** [comment]
Thank you, James! I'm gonna ping @pheiduck as he integrated your initial PR as well as the refactoring, but if I get a chance to sit at my desk today I will look to digest! :)

**Comment by peterlewis** [comment]
Thanks, @James-Stokes and @pheiduck, testing now.

**Review by pheiduck — APPROVED** [review]

**Pull request merged**
