### PR TITLE
Import json configurations with no PreShared-Key

### PR DESCRIPTION
**Pull request by pheiduck**
Import json configurations with no PreShared-Key (#341) from @t-oster
new Branch for testing and merge into `master`

### CODE REVIEW

**Comment by pheiduck** [comment]
@t-oster please test: `ghcr.io/wg-easy/wg-easy:development`

**Comment by pheiduck** [comment]
hold back for version 12

**Comment by t-oster** [comment]
Works for me. But I had to 'npm install bcrypt' before, but this is also true for master and may be because I am not using the dockerized version.

**Comment by willtho89** [comment]
Can also confirm this working. New creation, and export of clients is working as expected. 
Importing existing configs also works and I'm able to connect without the psk.

**Pull request merged**
