### PR TITLE
Fix detailed stats 2

### PR DESCRIPTION
**Pull request by suxscribe**
- Fixed error in changelog.json
- Updated css
- Some refactoring on fetching uiDetailedStats

Hope everything's ok this time :)

### CODE REVIEW

**Comment by pheiduck** [comment]
@suxscribe Thanks for your Patches, the changelog one needs to be cherry-picked.

**Comment by pheiduck** [comment]
@suxscribe Until now, haven't enough time for testing. If you want try out development build and report back if it working or not.

**Comment by peterlewis** [comment]
@suxscribe This PR is looking better by the day. Thank you. Any chance you could make it so that when stats are above buttons, that they are right-aligned to the buttons? Think it would look a little bit neater. Thank you!

**Comment by suxscribe** [comment]
> make it so that when stats are above buttons, that they are right-aligned to the buttons

@peterlewis I think I tried that while working on mobile layout and preferred current alignment. I'll give it another try in a few days

**Pull request merged**
