### PR TITLE
add ability to change localtime eg `docker logs`

### PR DESCRIPTION
**Pull request by pheiduck**
Closes: https://github.com/wg-easy/wg-easy/discussions/766

### CODE REVIEW

**Comment by pheiduck** [comment]
Hold back for version 12.

**Review by bastianleicht — APPROVED** [review]
Worked on my machine, thanks 👍

**Comment by pheiduck** [comment]
> Worked on my machine, thanks 👍

When you call `docker log` it reports the time from your host?

**Comment by pheiduck** [comment]
maybe this: `2024-01-26T17:10:17.705Z` could not be changed?
It should be: `2024-01-26T18:10:17.705Z`

**Pull request closed without merging**
