### PR TITLE
fixup: WG_PORT in config.js

### LINKED ISSUE #1032: Unable to connect after upgrade to version 13
With the upgrade to version 13 I cannot connect with my mobile phone to the VPN of my Raspberry Pi5 (Debian bookworm based OS).
In the logs I see the connection but in reality I am not connected, in fact the connection point is not visible.

If I downgrade to version 12 everything starts working properly again, so the portforward in my router is certainly configured correctly.
I await your news

Thank you

### LINKED ISSUE #1045: Wireguard not working in release tagged 13 (latest)
I just updated to version 13, the application works, but Wireguard does not. I rolled back to 12 and everything works again. There are no errors in the logs. I don't know what additional information there is.

### PR DESCRIPTION
**Pull request by pheiduck**
Fixes #1032
Fixes #1045

### CODE REVIEW

**Comment by kaaax0815** [comment]
This should also update the README

**Comment by pheiduck** [comment]
@kaaax0815 please take a look at the updated readme, hope it does not confuse...

**Comment by jhedd** [comment]
Might want to also add to the updating section of the README for people updating to release 13.

As a user who came here because things 'just stopped working', when following the recommended update procedure of 

> docker compose up --detach --pull always

there's no indication there's any difference between releases 12 and 13, and a three-word change to the setup options table is going to be easily missed.  Since the only bugs on this issue are closed there's going to be limited visibility for users who are trying to diagnose why their installations simply stopped working.

**Comment by pheiduck** [comment]
> Might want to also add to the updating section of the README for people updating to release 13.
> 
> As a user who came here because things 'just stopped working', when following the recommended update procedure of
> 
> > docker compose up --detach --pull always
> 
> there's no indication there's any difference between releases 12 and 13, and a three-word change to the setup options table is going to be easily missed. Since the only bugs on this issue are closed there's going to be limited visibility for users who are trying to diagnose why their installations simply stopped working.

Please make PR to include your recommendation.

**Pull request merged**
