### PR TITLE
Add IPv6 support

### PR DESCRIPTION
**Pull request by arankaren**
wg-easy-example

### CODE REVIEW

**Comment by sureshamk** [comment]
I used this PR version docker image(sureshamk/wg-easy:ipv6), I am able to see the ipv6 address in the UI but the client can not able to connect with the internet. Please check

**Comment by jeremyjohn** [comment]
Thanks, this works fine. 
The only thing I would add is the option to change the subnet mask and address prefix.

**Comment by marat2509** [comment]
Can't determine IP address.
Logs:
`wg-easy    | 2022-10-07T11:21:29.595Z Server Listening on http://127.0.0.1:51821
wg-easy    | 2022-10-07T11:21:29.597Z WireGuard Loading configuration...
wg-easy    | 2022-10-07T11:21:29.600Z WireGuard Configuration loaded.
wg-easy    | 2022-10-07T11:21:29.600Z WireGuard Config saving...
wg-easy    | 2022-10-07T11:21:29.602Z WireGuard Config saved.
wg-easy    | $ wg-quick down wg0
wg-easy    | $ wg-quick up wg0
wg-easy    | Error: Command failed: wg-quick up wg0
wg-easy    | [#]
wg-easy    | [#] ip link add wg0 type wireguard
wg-easy    | [#] wg setconf wg0 /dev/fd/63
wg-easy    | Unable to parse IP address: `undefined'
wg-easy    | Configuration parsing error
wg-easy    | [#] ip link delete dev wg0
wg-easy    |
wg-easy    |     at ChildProcess.exithandler (child_process.js:383:12)
wg-easy    |     at ChildProcess.emit (events.js:400:28)
wg-easy    |     at maybeClose (internal/child_process.js:1058:16)
wg-easy    |     at Process.ChildProcess._handle.onexit (internal/child_process.
js:293:5) {
wg-easy    |   killed: false,
wg-easy    |   code: 1,
wg-easy    |   signal: null,
wg-easy    |   cmd: 'wg-quick up wg0'
wg-easy    | }`

Runned: `docker run wg-easy_wg-easy ip link delete dev wg0`

**Comment by Pr0mises** [comment]
> I used this PR version docker image(sureshamk/wg-easy:ipv6), I am able to see the ipv6 address in the UI but the client can not able to connect with the internet. Please check

Did you manage to get it working?

**Comment by sparkyvxcx** [comment]
> Can't determine IP address. Logs: https://yaso.su/PqaxbQks
> 
> Screenshot_20221007-142404_Termius

It seems you are trying this PR version through modifying `docker-compose.yml` and `docker-compose up` right? I was doing the same thing, and this exact error appeared.

Switch to build the image first then run the image follow the instruction from README.md seems work.

```
docker build -t ipv6-wg-easy:latest
```

then
```
docker run -d \
  --name=wg-easy \
  -e WG_HOST=hostname \
  -e PASSWORD=random-password-for-testing \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --sysctl="net.ipv6.conf.all.disable_ipv6=0" \
  --sysctl="net.ipv6.conf.all.forwarding=1" \
  --sysctl="net.ipv6.conf.default.forwarding=1" \
  --sysctl="net.ipv6.conf.eth0.proxy_ndp=1" \
  --restart unless-stopped \
  ipv6-wg-easy:latest
```

but still client failed to get internet access through wireguard server...

**Comment by MrTlyer** [comment]
docker run -d \
  --name=wg-easy \
  -e WG_HOST=xx.xx.xx \
  -e PASSWORD=xxxxxxx \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --sysctl net.ipv6.conf.all.disable_ipv6=0 \
  --sysctl net.ipv6.conf.all.forwarding=1 \ 
  --restart unless-stopped \
  weejewel/wg-easy

这样是不是就可以同时支持V4和V6了？

**Pull request closed without merging**
